apiVersion: v1
kind: Secret
metadata:
  name: incident-secrets
type: Opaque
stringData:
  GROQ_API_KEY: "replace-with-real-key-in-prod"
  POSTGRES_USER: "incident_user"
  POSTGRES_PASSWORD: "incident_pass"
  POSTGRES_DB: "incidents"
  DATABASE_URL: "postgresql://incident_user:incident_pass@timescaledb:5432/incidents"
  REDIS_URL: "redis://redis:6379"
  WEAVIATE_URL: "http://weaviate:8080"
  JAEGER_URL: "http://jaeger:16686"
  TELEMETRY_URL: "http://telemetry-collector:8001"
  KUBE_ENABLED: "true"
